export const terms = {
    words: [
        "clothing","yourself","story","willing","now","chamber","highest","die","oil","law","plane","huge","planned","third","anything","easier","clock","smaller","border","it","apart","gradually","topic","soldier","porch","society","better","combination","larger","angry","tin","failed","extra","event","test","paper","fall","told","teacher","cold","donkey","which","detail","fifth","harbor","explore","burn","development","century","new","information","secret","joy","promised","driver","large","powerful","length","carefully","tube","alphabet","stay","work","belt","little","change","worried","south","stand","screen","hair","scale","sharp","rapidly","steep","note","fish","ability","couple","if","become","loud","excitement","back","string","name","late","president","specific","citizen","health","shaking","several","suppose","dirty","older","shadow","hello","brass","dangerous","solve","shoe","shirt","cross","got","melted","greatly","quite","get","tiny","animal","nor","kids","picture","sick","port","greatest","stuck","answer","attempt","stock","anyway","nearly","allow","complex","pig","stranger","previous","catch","taken","foreign","moment","hide","southern","movement","sing","reach","tone","lungs","folks","largest","dawn","held","slipped","spread","train","village","wonderful","characteristic","stick","universe","under","slip","saved","bend","afraid","particles","offer","so","pie","plain","question","instead","enter","stove","table","ourselves","pull","oxygen","corn","engineer","has","poetry","milk","choose","second","whale","are","radio","ready","push","student","know","led","smooth","cannot","worry","atomic","yard",
        "getting","read","wish","children","cattle","crack","race","chair","call","molecular","here","cup","dull","picture","brother","lift","customs","mean","bent","wise","dance","eye","globe","brave","earn","tape","made","fly","under","grade","spring","tell","waste","national","chemical","than","duty","small","mighty","fighting","lunch","arrive","rule","again","bottle","heading","powerful","foreign","climate","lack","railroad","consider","flow","someone","top","diagram","invented","sail","mile","north","summer","strength","eleven","lesson","proper","gift","nothing","ought","excitement","stepped","species","particularly","roll","graph","section","thick","grade","married","nation","grade","drive","indicate","balance","run","colony","search","customs","differ","sang","hollow","replied","caught","classroom","cool","certain","aware","coal","origin","golden","indicate","inch","particular","anyone","longer","brother","sentence","clearly","harder","scientific","loud","feel","feel","knowledge","composition","donkey","throughout","butter","negative","setting","beat","indeed","one","sat","result","mice","basic","gradually","friendly","greater","rose","ride","worried","eat","sing","pressure","wash","fed","stock","sure","figure","great","purple","promised","began","rod","six","afternoon","city","five","rice","brought","that","track","quietly","wherever","protection","gradually","straight","south","birthday","major","scene","sitting","bite","specific","gray","push","corner","official","forth","gentle","fifty","forest","influence","load","home","perfectly","serious","that","burst","wall","food","everything","sky","diameter","rubber","straw","combine","hold"
    ],
    duds: [
        "%($(","^","","$:!>{","/","^<!","#","=!$)<","*","$^)>#&","}$/$$)","%)/*}*","*&=$$","=$(","%/=",":}!/","/{^_","%*_*","=&:",")#%:#>","$/)*","^#>#&","!","/&/_","*=&","%#=","=&__$&","^_:",":",")*}#&","($!",")_<}}=",">&<(","%!$!!{","}%","%_//<","/{:}!{","){/#","&*","=",")%<","!{_/=","#:$)$(","{(^!<","_{<}","^&","_<",")%",":&/>#","$<%((",">:","&)%}","^_<","%*^{","$=>)}","!^","&/!}^^","%/!#^<","&&/$","#/",")#","!/*","<%*&","%&^!}&","><)(/%","}=_/*","!)>&&",">##&^:","_^{","$^}","__<","((",")^_:_!","#/$*","!{_)(_","%={",")!:_^",">_/{_>","%","<)/%/(","}*!/<","%&=$_^","}",")/>}!","=)<","<$","&==#","_$_","!{","<*^>>!","{>#","*<{*}=","#$(","&!(","_(}",">}{_&(","&*$:=^","#^!","{}_&^:","{","_=#)","}=","=(:_#",")>","(*#",")%_}>%","{!*_","}<>&(!","_&_=/","=^^=","{(","&","^!",")}<!$>",":}()","/=#",">#","{/{)<}","&=:","#!_/","{&#}&",">#}","=${$","^/:$<)","*/#^$","$/^%","=/=):*","^&!)>{","{!$}&{","_","!#(<(","#<{#/)","://${","{#","#$","$)/&","{^_=","={^&<%",":%","(^","<","^{","!>))=_","$","#(^<","*>{%&","!:$/$=","$^)","^#^)/=","#})","^%/","__","(&!",")","<={}<","{^",">#)", "()^!^","{>:","^&>#>#","=!$*)*","}${*=",":%*","}}=>","^:*)^",":","*","#=:&",":=>","","&{})","<%=","_!*_$(","!",")^/","{(",":$:=/^","(#{<","!<#{","_>}!","^/)(<","::",":&}_#","!","$}>:}","&!","<^)*","}#)","_^#","(>/:}","=<}*=","{","(^","#{#^}_",":^$%","",":}",">=/&#>","=}","!$!&=","","<:","",":!)(","&%{&(","(}^:*","=^#*%","*=","$#<&","#!","_{&","&&!>:","<#!&#{","!${#","#",")*%=(","<(!","{)$!#","(/_%:","$>","){!{{=","^:%=$","#^:(","}_#/_=","(>*","^(>:","","}","","($:!/!",">",")_<",">",")^__!","&!<}(!","${:",":_/$","*",">","%&(#:=","&</","}:","<_&({_","::/",")","(","","","_","{","!&^_}","",")","{/{^","(/:$>","^{","}_=","!%><#","",">{^!=","","&&",":=#%#","$*{^=^","^<","){>","$","","#!:<","^<==","{>{^{","","{}(","!/(&!*","","#}!","/<(%","","","$$^(","","(<(","%*","<_%^/(","%^",")<{>>*",")^<*=)","^=%>=","(&","","_!)#","","/^!","","<<//<",":)","","","/(_","><{{(","((=$<=",":>__$/","","(^!{{","#{#(<_","{#$/#","{}^","(","/=","","!&)&:*","<=/","}>(/{^","^_>!^="
    ],
    fillers: ['!','#','$','%','&','(',')','*','/','_',':','<','=','>','{','}','^'],
}

export default terms;